server:
  port: '8090'

eureka:
  instance:
    hostname: eureka-server
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
    prefer-ip-address: true

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/banking-nttdata-bootcamp/gateway
    discovery:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi
          uri: http://eureka-server:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        #routes[0]:
        #id: bootcamp-customer
        #predicates: Path=/customer/**
        #filters: StripPrefix=1
        #uri: lb://bootcamp-customer
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: gateway

springdoc:
  swagger-ui:
    urls:
      - name: customer
        url: /customer/api-docs/
      - name: passive
        url: /passive/api-docs/
      - name: active
        url: /active/api-docs/
      - name: deposit
        url: /deposit/api-docs/
      - name: payment
        url: /payment/api-docs/
      - name: charge-consumption
        url: /charge-consumption/api-docs/
      - name: withdrawal
        url: /withdrawal/api-docs/
      - name: balance
        url: /balance/api-docs/
      - name: movement
        url: /movement/api-docs/
